//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.11 at 10:11:28 PM CEST 
//


package parts;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the parts package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: parts
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Car }
     * 
     */
    public Car createCar() {
        return new Car();
    }

    /**
     * Create an instance of {@link Car.Parts }
     * 
     */
    public Car.Parts createCarParts() {
        return new Car.Parts();
    }

    /**
     * Create an instance of {@link Car.Assemblies }
     * 
     */
    public Car.Assemblies createCarAssemblies() {
        return new Car.Assemblies();
    }

    /**
     * Create an instance of {@link Car.Parts.Part }
     * 
     */
    public Car.Parts.Part createCarPartsPart() {
        return new Car.Parts.Part();
    }

    /**
     * Create an instance of {@link Car.Assemblies.Assembly }
     * 
     */
    public Car.Assemblies.Assembly createCarAssembliesAssembly() {
        return new Car.Assemblies.Assembly();
    }

}
