//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.11 at 10:12:08 PM CEST 
//


package instructions;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the instructions package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: instructions
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InstructionSeq }
     * 
     */
    public InstructionSeq createInstructionSeq() {
        return new InstructionSeq();
    }

    /**
     * Create an instance of {@link InstructionSeq.Instructions }
     * 
     */
    public InstructionSeq.Instructions createInstructionSeqInstructions() {
        return new InstructionSeq.Instructions();
    }

    /**
     * Create an instance of {@link InstructionSeq.Instructions.Instruction }
     * 
     */
    public InstructionSeq.Instructions.Instruction createInstructionSeqInstructionsInstruction() {
        return new InstructionSeq.Instructions.Instruction();
    }

    /**
     * Create an instance of {@link InstructionSeq.Instructions.Instruction.Actions }
     * 
     */
    public InstructionSeq.Instructions.Instruction.Actions createInstructionSeqInstructionsInstructionActions() {
        return new InstructionSeq.Instructions.Instruction.Actions();
    }

    /**
     * Create an instance of {@link InstructionSeq.Instructions.Instruction.Actions.Action }
     * 
     */
    public InstructionSeq.Instructions.Instruction.Actions.Action createInstructionSeqInstructionsInstructionActionsAction() {
        return new InstructionSeq.Instructions.Instruction.Actions.Action();
    }

    /**
     * Create an instance of {@link InstructionSeq.Instructions.Instruction.Actions.Action.Resources }
     * 
     */
    public InstructionSeq.Instructions.Instruction.Actions.Action.Resources createInstructionSeqInstructionsInstructionActionsActionResources() {
        return new InstructionSeq.Instructions.Instruction.Actions.Action.Resources();
    }

    /**
     * Create an instance of {@link InstructionSeq.Instructions.Instruction.Actions.Action.Resources.ItemsToAssemble }
     * 
     */
    public InstructionSeq.Instructions.Instruction.Actions.Action.Resources.ItemsToAssemble createInstructionSeqInstructionsInstructionActionsActionResourcesItemsToAssemble() {
        return new InstructionSeq.Instructions.Instruction.Actions.Action.Resources.ItemsToAssemble();
    }

    /**
     * Create an instance of {@link InstructionSeq.Instructions.Instruction.Actions.Action.Resources.Operators }
     * 
     */
    public InstructionSeq.Instructions.Instruction.Actions.Action.Resources.Operators createInstructionSeqInstructionsInstructionActionsActionResourcesOperators() {
        return new InstructionSeq.Instructions.Instruction.Actions.Action.Resources.Operators();
    }

    /**
     * Create an instance of {@link InstructionSeq.Instructions.Instruction.Actions.Action.EndItem }
     * 
     */
    public InstructionSeq.Instructions.Instruction.Actions.Action.EndItem createInstructionSeqInstructionsInstructionActionsActionEndItem() {
        return new InstructionSeq.Instructions.Instruction.Actions.Action.EndItem();
    }

    /**
     * Create an instance of {@link InstructionSeq.Instructions.Instruction.Actions.Action.Resources.Machine }
     * 
     */
    public InstructionSeq.Instructions.Instruction.Actions.Action.Resources.Machine createInstructionSeqInstructionsInstructionActionsActionResourcesMachine() {
        return new InstructionSeq.Instructions.Instruction.Actions.Action.Resources.Machine();
    }

    /**
     * Create an instance of {@link InstructionSeq.Instructions.Instruction.Actions.Action.Resources.ItemsToAssemble.Item }
     * 
     */
    public InstructionSeq.Instructions.Instruction.Actions.Action.Resources.ItemsToAssemble.Item createInstructionSeqInstructionsInstructionActionsActionResourcesItemsToAssembleItem() {
        return new InstructionSeq.Instructions.Instruction.Actions.Action.Resources.ItemsToAssemble.Item();
    }

    /**
     * Create an instance of {@link InstructionSeq.Instructions.Instruction.Actions.Action.Resources.Operators.Operator }
     * 
     */
    public InstructionSeq.Instructions.Instruction.Actions.Action.Resources.Operators.Operator createInstructionSeqInstructionsInstructionActionsActionResourcesOperatorsOperator() {
        return new InstructionSeq.Instructions.Instruction.Actions.Action.Resources.Operators.Operator();
    }

}
